### ISSUE TITLE
Frames number limit

### ISSUE THREAD

**Issue by avwarez** [datenstau/A9_PPPP#1]
Hi, thanks for your work. I noticed the video freezes after about 10 minutes, maybe because of the variable that contains the number of frame reaches the max value of 65535.

**Comment by datenstau** [comment]
Hi, you're right, something is overflowing.
But it's not the variable that stores the frame count, it's the MSG_DRW packet index the cam is sending.

I guess I've handled this now. Check out my last commit. I've tested 3 overflows and the video was still running.

I've never tested the video playback for this amount of time. This project was just a little training in reverse engineering network protocols, so this code was not meant to be used in production. 
But feel free to test and improve it!
